"""Every number the README quotes about a run must match the run it cites.

The README says of the scorecard that "both come from the same reduction, so they
cannot disagree". They can, and they did: the table claimed retrieval 100% (12/12)
and accuracy 3 of 10 while ``reports/scorecard.json`` held 83% (10/12) and 5 of 12,
and the supporting line quoted a mean precision of 0.52 against a measured 0.4773.
Nothing failed, because nothing was checking -- a scorecard is regenerated by
``make evals`` and the prose about it is edited by hand, so they drift apart every
time a suite is re-run and the drift is invisible until a reader opens both.

These read the artefact and search the README for what it should say. They are not
a substitute for running the suite; they are what stops the report of a suite from
outliving it.
"""

from __future__ import annotations

import json
import re
from typing import Any

import pytest

from src.agent.graph import answer_toolkit, pipeline_nodes
from src.ui.status import PROJECT_ROOT

README = PROJECT_ROOT / "README.md"
SCORECARD = PROJECT_ROOT / "reports" / "scorecard.json"


def _scorecard() -> dict[str, Any]:
    """Load the last scorecard, skipping the suite when none has been written.

    Returns:
        The parsed summary ``make evals`` wrote.
    """
    if not SCORECARD.is_file():
        pytest.skip("no scorecard yet; run `make evals`")
    return json.loads(SCORECARD.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def readme() -> str:
    """The README with its markdown emphasis stripped.

    Searched as plain text, because the claim under test is the figure and not
    how it is marked up: the table writes ``**83%** (10/12)`` and a check that
    demanded the asterisks would break on a bolding change and pass on a wrong
    number, which is exactly backwards.

    Returns:
        The text, with ``*`` and ``_`` removed.
    """
    return README.read_text(encoding="utf-8").replace("*", "").replace("_", "")


STOCHASTIC_SUITES = frozenset({"Retrieval"})
"""Suites whose score legitimately moves between two runs of the same code.

Retrieval expands the query with a live model call, so the same corpus and the same
twelve questions do not give the same score twice: the two marginal cases turn on
whether expansion reaches them. Measured across four runs in one afternoon the pass
rate was 11/12 or 12/12 and mean precision ran 0.57 to 0.66.

That is a fact about the measurement, not a defect, and pinning it to the digit made
this file fail on every ``make evals`` -- which trains a reader to edit the number
until the build goes green, the exact habit the pin exists to prevent. So a
stochastic suite is held to the *neighbourhood* of what was measured and a
deterministic one is still held to the digit.
"""

CASES_TOLERANCE = 1
"""How many cases a stochastic suite's quoted score may sit away from the measured one."""

MEAN_TOLERANCE = 0.12
"""How far a quoted retrieval mean may sit from the measured one.

Wider than the spread observed across four runs, so an honest document passes, and far
narrower than the distance to a figure somebody made up.
"""


def test_each_suite_score_is_quoted_as_measured(readme: str) -> None:
    """The README's score table matches the scorecard's own percentages.

    Exactly, for a suite that measures the same thing twice running. Within one case
    for a suite that does not -- see :data:`STOCHASTIC_SUITES`.

    Args:
        readme: The README text.
    """
    for suite in _scorecard()["scores"]:
        if not suite["ran"]:
            continue
        quoted = f"{suite['percent']} ({suite['passed']}/{suite['total']})"
        if suite["name"] not in STOCHASTIC_SUITES:
            assert quoted in readme, (
                f"{suite['name']} scored {quoted} in reports/scorecard.json and the "
                f"README does not say so anywhere"
            )
            continue
        claimed = [
            int(passed)
            for passed, total in re.findall(r"\((\d+)/(\d+)\)", readme)
            if int(total) == suite["total"]
        ]
        assert claimed, (
            f"{suite['name']} is scored out of {suite['total']} and the README quotes "
            f"no score with that denominator"
        )
        assert any(abs(value - suite["passed"]) <= CASES_TOLERANCE for value in claimed), (
            f"{suite['name']} scored {suite['passed']}/{suite['total']} and the README "
            f"quotes {claimed}, none of them within {CASES_TOLERANCE} case of it"
        )


@pytest.mark.parametrize(
    ("field", "phrase"),
    [
        ("mean_precision", "mean precision@4"),
        ("mean_reciprocal_rank", "mean reciprocal rank"),
    ],
)
def test_retrieval_supporting_numbers_are_quoted_as_measured(
    readme: str, field: str, phrase: str
) -> None:
    """Precision and reciprocal rank are quoted near the value measured.

    Near rather than at: both are means over a search whose query expansion is a model
    call, so they move between runs. See :data:`STOCHASTIC_SUITES` for why holding
    them to the digit was the wrong pin.

    The figure is read out of the sentence that names the metric, so this checks the
    number the README actually attaches to that phrase rather than whether the digits
    appear anywhere in the document.

    Args:
        readme: The README text.
        field: The scorecard key to check.
        phrase: The wording the README introduces that figure with.
    """
    measured = _scorecard()["retrieval"][field]
    quoted = [float(value) for value in re.findall(rf"{re.escape(phrase)} (\d\.\d+)", readme)]
    assert quoted, f"the README never writes {phrase!r} followed by a figure"
    assert all(abs(value - measured) <= MEAN_TOLERANCE for value in quoted), (
        f"retrieval.{field} is {measured:.4f} and the README quotes {quoted}, "
        f"further than {MEAN_TOLERANCE} from it"
    )


def test_the_router_count_is_quoted_as_measured(readme: str) -> None:
    """The README's "4 of 11 answerable questions" is the measured split.

    Args:
        readme: The README text.
    """
    retrieval = _scorecard()["retrieval"]
    sentence = (
        f"the labelled shelf for {retrieval['routed_correctly']} of "
        f"{retrieval['answerable']} answerable questions, left "
        f"{retrieval['routed_nowhere']} unrestricted and sent "
        f"{retrieval['routed_elsewhere']} elsewhere"
    )
    assert sentence in readme, f"the README does not say: {sentence!r}"


def test_the_accuracy_finding_is_quoted_as_measured(readme: str) -> None:
    """Both prose restatements of the accuracy result match the scorecard.

    The score appears three times -- once in the table and twice as prose -- and
    the prose is what went stale, so it is worth checking on its own.

    Args:
        readme: The README text.
    """
    accuracy = _scorecard()["accuracy"]
    assert f"{accuracy['solved']} of {accuracy['cases']}" in readme, (
        f"accuracy solved {accuracy['solved']} of {accuracy['cases']} and the README "
        f"states some other pair"
    )


def test_the_scorecard_says_no_model_graded_it() -> None:
    """The claim that nothing here is graded by a model is in the artefact too.

    The README rests a good deal on it, and it is a field rather than a promise
    precisely so that a run which did use a judge could not be reported as one
    that did not.
    """
    assert _scorecard()["graded_by_a_model"] is False


def test_the_counts_the_readme_states_about_itself(readme: str) -> None:
    """Corpus size and the tool count match what the code actually has.

    Args:
        readme: The README text.
    """
    notes = len(list((PROJECT_ROOT / "data" / "corpus").rglob("*.md")))
    assert f"{notes} notes" in readme, f"the corpus holds {notes} notes"
    assert f"{len(pipeline_nodes())} nodes" in readme, (
        f"the graph has {len(pipeline_nodes())} nodes"
    )
    assert len(answer_toolkit({})) == 8, (
        "the README calls this the eight tools; a ninth is added only when a "
        "reference bench is lent, and that one is named separately"
    )


def test_the_readme_states_one_test_count_and_one_doctest_count(readme: str) -> None:
    """The suite's size is quoted in several places, and they must agree.

    Not pinned to the real total, which changes with every test added and would
    make this a chore rather than a check. What it catches is the failure that
    actually happened: the README said 2703 tests in three places, 2717 in a
    fourth, 132 doctests in one and 133 in another. A reader cannot tell which is
    true, and a document that disagrees with itself is evidence against every
    other number in it.

    Args:
        readme: The README text.
    """
    import re

    def stated(unit: str) -> set[int]:
        found = re.findall(r"(\d[\d\u202f ,]*\d|\d)\s+" + unit + r"\b", readme)
        return {int(re.sub(r"[^\d]", "", value)) for value in found}

    counted = stated("tests")
    assert len(counted) <= 1, f"the README states {sorted(counted)} as its test count"
    docs = stated("doctests")
    assert len(docs) <= 1, f"the README states {sorted(docs)} as its doctest count"


def test_the_suite_scores_the_search_the_application_actually_ships() -> None:
    """The evaluated vector share and the shipped one are the same number.

    Three constants spell this: the library's fallback, the interface's default and
    the suite's. The first is allowed to differ -- it is what a bare ``retrieve()``
    gets. The other two are not, because a retrieval score measured at one weighting
    and an application shipped at another is a score about software nobody runs.
    """
    from src.evals.retrieval_cases import VECTOR_SHARE
    from src.ui.setting import DEFAULT_VECTOR_SHARE

    assert VECTOR_SHARE == DEFAULT_VECTOR_SHARE


def test_the_readme_documents_every_node_the_graph_has() -> None:
    """The "Node by node" table and the graph name the same seventeen nodes.

    The README states a node count in one place and lists the nodes in another,
    and the two drifted: it claimed seventeen while its own table described
    sixteen, with ``converge`` -- the node that draws the curves -- missing. A
    reader counting the table would have found the count wrong and had no way to
    tell which half was.

    Reads the file rather than taking the ``readme`` fixture, which strips markdown
    emphasis -- and here the emphasis is the syntax being matched.
    """
    import re

    from src.agent.graph import build_graph

    raw = README.read_text(encoding="utf-8")
    block = raw[raw.index("<summary><b>Node by node</b>") :]
    block = block[: block.index("</details>")]
    listed = set(re.findall(r"\| \*\*([a-z_]+)\*\* \|", block))
    actual = {name for name in build_graph().get_graph().nodes if not name.startswith("__")}

    assert listed == actual, (
        f"undocumented nodes: {sorted(actual - listed)}; "
        f"documented but absent from the graph: {sorted(listed - actual)}"
    )
    assert f"{len(actual)} nodes" in raw, (
        f"the graph has {len(actual)} nodes and the README states some other number"
    )


def test_the_mermaid_diagram_draws_every_node_the_graph_has() -> None:
    # The README said "seventeen nodes exist" directly above a diagram with sixteen
    # boxes: `converge` was missing. A hand-drawn picture of a generated structure
    # goes stale the first time the structure changes, and nothing counted the boxes.
    import re

    from src.agent.graph import pipeline_nodes

    diagram = re.search(r"```mermaid\n(.*?)```", README.read_text(encoding="utf-8"), re.DOTALL)
    assert diagram is not None, "the README lost its graph diagram"
    drawn = set(re.findall(r"^    ([a-z_]+)\[", diagram.group(1), re.MULTILINE))
    missing = set(pipeline_nodes()) - drawn

    assert not missing, f"the diagram does not draw: {', '.join(sorted(missing))}"


def test_the_drawn_graph_figure_covers_every_node_too() -> None:
    # Two pictures of one graph, and they have to agree. The script raises at draw
    # time if its layout is short a node, but `make figures` is not part of `make
    # check`, so a node added today would not go red until somebody redrew. Read by
    # parsing rather than importing: scripts/ is not a package, and importing one of
    # its modules from here has mypy see the same file under two module names.
    import ast

    from src.agent.graph import pipeline_nodes

    tree = ast.parse((PROJECT_ROOT / "scripts/draw_agent_graph.py").read_text(encoding="utf-8"))
    drawn: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.AnnAssign) and getattr(node.target, "id", "") == "LAYOUT":
            assert isinstance(node.value, ast.Dict)
            drawn = {
                key.value
                for key in node.value.keys
                if isinstance(key, ast.Constant) and isinstance(key.value, str)
            }

    assert drawn, "the figure's LAYOUT table could not be read"
    assert drawn == set(pipeline_nodes())


def test_the_workflow_figure_counts_agree_with_the_code_they_describe() -> None:
    # The master slide states "7 pages" and "17 nodes" in its label column. Both are
    # counts of things that change, printed into a picture nobody re-reads.
    import ast

    from src.agent.graph import pipeline_nodes
    from src.ui import panels

    tree = ast.parse(
        (PROJECT_ROOT / "scripts/draw_project_workflow.py").read_text(encoding="utf-8")
    )
    claims: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.AnnAssign) and getattr(node.target, "id", "") == "BANDS":
            assert isinstance(node.value, ast.Tuple)
            for band in node.value.elts:
                assert isinstance(band, ast.Tuple)
                claims += [
                    item.value
                    for item in band.elts
                    if isinstance(item, ast.Constant) and isinstance(item.value, str)
                ]

    assert claims, "the figure's BANDS table could not be read"
    assert f"{len(panels.PAGES)} pages" in " | ".join(claims), "the page count is wrong"
    assert f"{len(pipeline_nodes())} nodes" in " | ".join(claims), "the node count is wrong"
